import { AgentBase, AgentInput, AgentOutput, AgentAction, StreamCallback } from '../core/AgentBase';

type SummaryStyle = 'brief' | 'detailed' | 'bullets';

const STYLE_PROMPTS: Record<SummaryStyle, string> = {
  brief: `Provide a concise 2-3 sentence summary that captures the main point.
Keep it clear and direct. No bullet points.`,

  detailed: `Provide a comprehensive summary that includes:
- Main thesis or central idea
- Key supporting points
- Important details or examples
- Conclusion or implications

Use clear paragraphs and be thorough but not verbose.`,

  bullets: `Summarize in 3-5 bullet points.
Each bullet should capture a distinct key point.
Keep bullets concise but informative.
Format: - Point here`
};

export class SummaryAgent extends AgentBase {
  readonly name = 'summary';
  readonly description = 'Summarize notes and text content';
  readonly icon = 'file-text';

  // Keywords that indicate summarization intent
  private summaryKeywords = [
    'summarize', 'summary', 'tldr', 'tl;dr', 'brief', 'key points',
    'main points', 'overview', 'recap', 'digest', 'condense'
  ];

  canHandle(input: AgentInput): boolean {
    const query = input.query.toLowerCase();

    for (const keyword of this.summaryKeywords) {
      if (query.includes(keyword)) {
        return true;
      }
    }

    return false;
  }

  async execute(input: AgentInput, stream?: StreamCallback): Promise<AgentOutput> {
    this.validateInput(input);

    // Determine summary style from query
    const style = this.detectStyle(input.query);

    // Get content to summarize
    let content = input.context || input.query;

    // If no context provided, try to get current note
    if (!input.context) {
      const noteContent = await this.context.vault.getActiveNoteContent();
      if (noteContent) {
        content = noteContent;
      }
    }

    try {
      const response = await this.context.ollama.chat([
        { role: 'system', content: `You are a summarization assistant.\n\n${STYLE_PROMPTS[style]}` },
        { role: 'user', content: `Summarize the following:\n\n${content}` }
      ], stream);

      const actions: AgentAction[] = [
        {
          type: 'create_note',
          label: 'Save Summary',
          payload: {
            title: `Summary - ${new Date().toISOString().split('T')[0]}`,
            content: `# Summary\n\n${response}\n\n---\n*Generated by Jarvis*`,
            folder: '0-Inbox'
          }
        }
      ];

      return {
        content: response,
        type: 'markdown',
        metadata: {
          style,
          sourceLength: content.length,
          summaryLength: response.length,
          compressionRatio: (response.length / content.length * 100).toFixed(1) + '%'
        },
        actions
      };
    } catch (error) {
      throw new Error(`Summarization failed: ${error.message}`);
    }
  }

  /**
   * Detect the desired summary style from the query
   */
  private detectStyle(query: string): SummaryStyle {
    const q = query.toLowerCase();

    if (q.includes('brief') || q.includes('short') || q.includes('tldr') || q.includes('quick')) {
      return 'brief';
    }

    if (q.includes('detailed') || q.includes('comprehensive') || q.includes('thorough')) {
      return 'detailed';
    }

    if (q.includes('bullet') || q.includes('points') || q.includes('list')) {
      return 'bullets';
    }

    // Default to bullets
    return 'bullets';
  }
}
